config/routes.rb
Rails.application.routes.draw do
  #get 'categorise/index'
  #get 'categorise/show'
  get 'homes/top'
  get 'homes/about'
  get 'homes/unsubscribe'
  get 'homes/help'
  get 'rooms/search' => 'rooms#search'
  get 'rooms/topic' => 'rooms/topic'

  resources :clients, only: [:show, :edit, :update, :index, :destroy]
  get "clients/:id" => "client#show"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    post 'users/sign_up/complete' => 'users/registrations#complete'
  end

  resources :rooms, only: [:new,  :show, :index, :create] do
    post :confirm, action: :confirm, on: :new
  end

  root 'homes#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
   before_action :authenticate_user!, only: [:index, :edit]

  def correct_user #url直打ち防止
      @user = current_user.find_by(id: params[:id])
      unless @user
          redirect_to client_path
      end
  end

  def index
    @users = User.order("RAND()").page(params[:page]).per(10)
  end

  def edit
  	@user = User.find(params[:id])
    if  @user.id != current_user.id #url直打ち防止
        redirect_to client_path(current_user)
      end
  end

  def show
  	@user = User.find(params[:id])
    @message = @user.messages
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to client_path(@user)
  	else
      flash.now[:notice] = "入力が正しくありません"
  		render 'edit'
  	end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to homes_unsubscribe_path
  end

	private
  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :introduction)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<!-- エラーメッセージ -->
<% if flash[:notice] %>
 	<div class="alert alert-danger alert-dismissible fade show" role="alert">
	  	<strong>エラー</strong>　入力が正しくありません！
	  	<button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
	  	<span aria-hidden="true">&times;</span>
	  	</button>
	</div>
<% end %>

<!-- プロフィールの編集-->
<div class="big-box">
	<div class="my-info-box ">
		<h3 class="new-room">プロフィール</h3>
		<div class="my-info-box">
			<%= form_for @user,:url => {:action => :update} do |f| %>
				<h5 class="info-subject">ユーザ名</h5>
				<%= f.text_field :name, placeholder:"2文字以上20文字以内", size: "60*60", class: "info-text"  %>
				<h5 class="info-subject">自己紹介</h5>
				<%= f.text_area :introduction, class: "info-text-edit"  %>
				<h5 class="info-subject">メールアドレス</h5>
				<%= f.text_field :email, size: "60*60", class: "info-text" %>
				<h5 class="info-subject">プロフィール画像</h5>
				<%= f.attachment_field :profile_image, class: "info-text-no"  %>
				<div class="my-info-botton">
					<%= f.submit 'Update User' , class: "btn btn-lg btn-block btn-outline-success  last-btn" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/clients/index.html.erb
<% @users.each do |f| %>
	<div class="row">
		<div class="user-list c-btn hover2">
			<%= link_to client_path(f.id) do%>
				<div class="users-image">
					<%= attachment_image_tag f,  :profile_image, format: 'jpeg' ,fallback: "/images/noimage.jpeg", class: "users-image" %>
				</div>
				<div class="users-info">
					<h5 class="info-box">ユーザ名</h5>
					<% if f.name.nil? == false %>
						<h5 class="my-info-s"><%= f.name %></h5>
						<% else f.name.nil? == true %>
							<h5 class="my-info-s">名無しさん</h5>
					<% end %>

					<h5 class="info-box">自己紹介</h5>
					<% if f.introduction.nil? == true %>
						<h5 class="my-info-s">宜しくお願いします</h5>
						<% elsif f.introduction.length == 0 %>
							<h5 class="my-info-s">宜しくお願いします</h5>
						<% else f.introduction.nil? == false %>
							<h5 class="my-info-s"><%= simple_format(f.introduction) %></h5>
					<% end %>

					<h5 class="info-box">コメント数</h5>
						<h5 class="my-info-s"><%= f.messages.count %>pt</h5>
				</div>
			<% end %>
		</div>
	</div>
<% end %>
 <!-- ページネーション -->
<%= paginate @users, class: "page"  %>
 <!-- 戻るボタン -->
  <p id="pageTop"><a href="#"><i class="fas modoru fa-3x fa-arrow-circle-up"></i></a></p>
</div>

app/views/clients/show.html.erb
<div class="big-box">
	<div class="my-info-box">
	<h3 class="new-room">プロフィール</h3>
	<div class="my-info-box">
		<%= attachment_image_tag @user,  :profile_image, format: 'jpeg' ,fallback: "/images/noimage.jpeg" , class: "user-image" %>

		<h5 class="info-box">ユーザ名</h5>
		<% if @user.name.nil? == false %>
			<h5 class="my-info"><%= @user.name %></h5>
			<% else @user.name.nil? == true %>
			<h5 class="my-info">ユーザ名を登録してください</h5>
		<% end %>

		<h5 class="info-box">自己紹介</h5>
		<% if @user.introduction.nil? == true %>
			<h5 class="my-info">現在未記入です。<br>プロフィール充実させませんか？</h5>
			<% elsif @user.introduction.length == 0 %>
				<h5 class="my-info">現在未記入です。<br>プロフィール充実させませんか？</h5>
			<% else @user.introduction.nil? == false %>
				<h5 class="my-info"><%= simple_format(@user.introduction) %></h5>
		<% end %>

		<h5 class="info-box">最終ログイン日時</h5>
		<% if @user.current_sign_in_at == nil? %>
			<h5 class="my-info"><%= @user.current_sign_in_at.strftime("%Y-%m-%d") %></h5>
			<% else %>
				<h5 class="my-info"><%= @user.created_at.strftime("%Y-%m-%d") %></h5>
		<% end %>

		<h5 class="info-box">コメント数</h5>
		<% if @user.messages.count == 0 %>
			<h5 class="my-info">まだコメントされていません</h5>
			<% else %>
				<h5 class="my-info">コメント数は<%= @user.messages.count %>ptです</h5>
		<% end %>


		<!-- current_userにしかメールアドレス、編集、退会ボタンを表示させない-->
		<% if @user == current_user %>
			<h5 class="info-box">メールアドレス</h5>
			<h5 class="my-info"><%= @user.email %></h5>
			<div class="my-info-botton">
				<%= link_to edit_client_path, class: "btn btn-lg btn-block btn-outline-success" do %>
					<i class="fas fa-user-edit"></i>ユーザ情報編集
				<% end %>
				<div class="user-btn">
					<%= link_to destroy_user_session_path, method: :delete, class: "btn btn-lg btn-block btn-outline-info"   do %>
						<i class="fas fa-sign-out-alt"></i>ログアウト
					<% end %>
					<%= link_to"退会", client_path(@user.id),method: :delete, "data-confirm" => "退会しますか？", class: "btn btn-lg btn-block btn-outline-danger last-btn"%>
				</div>
			</div>
		<% end %>
	</div>
</div>