config/routes.rb
Rails.application.routes.draw do
  #get 'categorise/index'
  #get 'categorise/show'
  get 'homes/top'
  get 'homes/about'
  get 'homes/unsubscribe'
  get 'homes/help'
  get 'rooms/search' => 'rooms#search'
  get 'rooms/topic' => 'rooms/topic'

  resources :clients, only: [:show, :edit, :update, :index, :destroy]
  get "clients/:id" => "client#show"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    post 'users/sign_up/complete' => 'users/registrations#complete'
  end

  resources :rooms, only: [:new,  :show, :index, :create] do
    post :confirm, action: :confirm, on: :new
  end

  root 'homes#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<div class="big-big4">
  	<div class="big-box">
    	<div class="my-info-box">

			<h2 class="new-room">EWSとは</h2>
			<h4 class="about1">Empathy With Someoneの略で「誰かと共感する」</h4>
			<h4 class="about2">あなたが思ったことを世界中の人と共有してみませんか？</h4>
      <div id="btn-login">
        <h3 id="login-click">こちらから</h3>
      </div>
      <div id="login">
        <h4 id="click-title">簡単登録！</h4>
        <%= link_to 'ログイン', new_user_session_path, class: "click-start" %>
        <%= link_to '新規登録', new_user_registration_path, class: "click-start"  %>
      </div>
		</div>
	</div>
</div>

app/views/homes/help.html.erb
<div class="help">
	<h2 class="help-title">よくある質問</h2>
	<div class="cp_qa">
		<div class="cp_actab">
		<input id="cp_tabfour011" type="checkbox" name="tabs">
		<label for="cp_tabfour011">チャットルームの作成方法がわかりません</label>
			<div class="cp_actab-content">
				<p>画面左上に”NEW ROOM”があります。そこからルームの新規作成が出来ます。</p>
			</div>
		</div>
		<div class="cp_actab">
		<input id="cp_tabfour012" type="checkbox" name="tabs">
		<label for="cp_tabfour012">チャットのやり方が分かりません</label>
			<div class="cp_actab-content">
				<p>チャットの一覧ページからお好きなルームに入って下さい。そこから入力フォームにメッセージを入力していただくだけでチャットが出来ます。</p>
			</div>
		</div>
		<div class="cp_actab">
		<input id="cp_tabfour013" type="checkbox" name="tabs">
		<label for="cp_tabfour013">登録情報の変更方法が分かりません</label>
			<div class="cp_actab-content">
				<p>登録情報の変更は”マイページ➡︎ユーザ情報編集”から出来ます。</p>
			</div>
		</div>
		<div class="cp_actab">
		<input id="cp_tabfour013" type="checkbox" name="tabs">
		<label for="cp_tabfour013">退会方法が分かりません</label>
			<div class="cp_actab-content">
				<p>退会はマイページから退会ボタンをクリックしていただき、確認ボタンを押してもらえれば退会が完了します。</p>
			</div>
		</div>
	</div>
</div>

app/views/homes/top.html.erb
<link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
<body class="top_body">
	<div id='stars'></div>
	<div id='stars2'></div>
	<div id='stars3'></div>
	<div id='title'>
		<span class="top-word">EWS</span>
		<br>
	  	<span class="top-word">Empathy With Someone</span>
	 	<div class="top-items">
	 		<%= link_to "使い方", homes_about_path, class: "btn-box1" %>
	 		<%= link_to "ログイン", new_user_session_path, class: "btn-box2" %>
	 		<%= link_to "新規登録", new_user_registration_path, class: "btn-box3" %>
	 	</div>
	</div>
</body>

app/views/homes/unsubscribe.html.erb
<meta http-equiv="refresh" content="5; url=top" />
<div class="big-big5">
  <div class="big-box">
    <div class="my-info-box ">
		<h5 class="about0">５秒後に自動で移動します</h5>
		<div>
			<h3 class="about1">ご利用ありがとうございました</h3>
			<h3 class="about2">またのご利用お待ちしております</h3>
		</div>
	</div>
</div>