config/routes.rb
Rails.application.routes.draw do
  #get 'categorise/index'
  #get 'categorise/show'
  get 'homes/top'
  get 'homes/about'
  get 'homes/unsubscribe'
  get 'homes/help'
  get 'rooms/search' => 'rooms#search'
  get 'rooms/topic' => 'rooms/topic'

  resources :clients, only: [:show, :edit, :update, :index, :destroy]
  get "clients/:id" => "client#show"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    post 'users/sign_up/complete' => 'users/registrations#complete'
  end

  resources :rooms, only: [:new,  :show, :index, :create] do
    post :confirm, action: :confirm, on: :new
  end

  root 'homes#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  
  enum category: { 喜び: 0, 悲しみ: 1, 不思議: 2, 憧れ: 3, 恐怖: 4, 後悔: 5, 期待: 6, 怒り: 7 }

  validates :title, presence: true, length: { in: 1..100}
  validates :detail, presence: true, length: { in: 1..200}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true).order(id: "DESC").page(params[:page]).per(10)
  end

  def topic
    @random = Room.order("RAND()").limit(5)
  end

  def new
    @room = Room.new
  end

  def confirm
    @room = Room.new(room_params)
    render :new unless @room.valid?
  end

  def search
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true).order(id: "DESC")
    @count = @rooms.count
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.order(id: "DESC")
  end

  def create
     @room = Room.new(room_params)
     if params[:back]
       render :new
       return
     end

     if @room.save
      redirect_to @room
    else
      flash.now[:notice] = "入力が正しくありません"
      render "rooms/new"
    end
  end

  private
    def room_params
        params.require(:room).permit(:title , :detail, :category)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/confirm.html.erb
<!-- ルーム作成-->
<div class="big-box">
	<h3 class="new-room">ルーム内容の確認</h3>
	<div class="my-info-box ">
		<%= form_for @room do |f| %>
		  	<h5 class="info-box">タイトル</h5>
        <p>
          <%= f.hidden_field :title %>
	  	     <%= @room.title %>
         </p>
		  	<h5 class="info-box">説明文</h5>
        <p>
          <%= f.hidden_field :detail%>
	  	     <%= @room.detail %>
         </p>
        <h5 class="info-box">カテゴリ</h5>
        <p>
		  	   <%= f.hidden_field :category %>
           <%= @room.category %>
         </p>
         <h5 class="confirm-btns">
	          <%= f.submit "Room作成", class: "btn-confirm-1" %>
            <%= f.submit '戻る', name: 'back', class: "btn-confirm-2" %>
        </h5>
		<% end %>
	</div>
</div>

app/views/rooms/index.html.erb
<div>
  <!-- ransack 検索 -->
  <div class="ransack-box">
  	<%= search_form_for @q, url: rooms_search_path do |f| %>
      <%= f.search_field :title_or_detail_cont, size: "20px", placeholder: "\uf002" "キーワードを入力", class: 'fa seach-bar' %>
      <div class="ransack-btn">
        <%= f.submit "検索", class:"btn btn-outline-primary rounded-pill" %>
      </div>
    <% end %>
  </div>


  <!-- ransack ソート -->
    <div class="box29">
      <div class="box-title">
        <p class="box-title2">並び順</p>
        <%= sort_link(@q, :title, "・タイトル") %>
        <%= sort_link(@q, :category, "・カテゴリ") %>
        <%= sort_link(@q, :created_at, '・ルーム作成日') %>
      </div>

      <!-- チャットルーム一覧 -->
      <div class="box-title3">
        <% @rooms.each do |room| %>
          <div class="room-box">
            <%= link_to room_path(room) do %>
              <p>ルーム：<%= room.title %></p>
              <p>内容：<%= truncate(room.detail, length: 20) %></p>
              <p>カテゴリ：<%= room.category %></p>
              <p>コメント数：<%= room.messages.count %>pt</p>
              <p style="float: left;">作成日：<%= room.created_at.strftime("%Y-%m-%d %H:%M") %></p>
              <p style="text-align:right"><%= time_ago_in_words(room.created_at) %>前</p>
            <% end %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ページネーション -->
<%= paginate @rooms, class: "page" %>

  <!-- 戻るボタン -->
  <p id="pageTop"><a href="#"><i class="fas modoru fa-3x fa-arrow-circle-up"></i></a></p>
</div>

app/views/rooms/new.html.erb
<!-- エラーメッセージ -->
<% if flash[:notice] %>
 	<div class="alert alert-warning alert-dismissible fade show" role="alert">
	  	<strong>エラー</strong>　入力が正しくありません！
	  	<button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
	  	<span aria-hidden="true">&times;</span>
	  	</button>
	</div>
<% end %>

<!-- ルーム作成-->
<div class="big-box">
	<h3 class="new-room">ルーム作成</h3>
	<div class="my-info-box ">
		<%= form_for @room, url: confirm_new_room_path do |f| %>
		  	<h5 class="info-box">タイトル</h5>
		  	<%= f.text_field :title , class: "info-text-3", placeholder: '2文字以上' %>
		  	<h5 class="info-box">説明文</h5>
		  	<%= f.text_area :detail  , class: "info-text-2 content", placeholder: '200文字以内' %>
        <p class="count "></p><!-- 文字のカウント -->
		  	<h5>カテゴリ<%= f.select :category, Room.categories.keys.to_a, {}, class: "category-box" %></h5>
		 	<div class="my-info-botton">
		  		<%= f.submit "確認", class: "btn btn-lg btn-block btn-outline-primary last-btn" %>
			</div>
		<% end %>
	</div>
</div>

app/views/rooms/search.html.erb
<div class="search-box">
	<h2>検索結果</h2>
	<% if @count == 0 %>
		<h3 class="search_conut">他のキーワードで検索してみてください</h3>

		<% elsif %>
		<h3 class="search_conut"><span><%= @count %><span class="search">件ヒットしました</span></h3>
		<% @rooms.each do |room| %>
		  <div class="room-box">
		    <%= link_to room_path(room) do %>
		      <p>ルーム：<%= room.title %></p>
		      <p>内容：<%= truncate(room.detail, length: 20) %></p>
		      <p>カテゴリ：<%= room.category %></p>
		      <p>コメント数：<%= room.messages.count %>pt</p>
		      <p style="float: left;">作成日：<%= room.created_at.strftime("%Y-%m-%d %H:%M") %></p>
		      <p style="text-align:right"><%= time_ago_in_words(room.created_at) %>前</p>
		    <% end %>
		  </div>
		<% end %>
	<% end %>
</div>

app/views/rooms/show.html.erb
<div class="room-show">
	<div class="container">
		<div class="row">
			<div class="col-3">
				<div class="aaa">
					<h5 class="room-title">ルーム名</h5>
					<p class="room-info-1"><%= @room.title %></p>
				</div>
				<div class="aaa">
					<h5 class="room-title">内容</h5>
					<p class="room-info-1"><%= @room.detail %></p>
				</div>
			</div>
			<div class="col-9">
				<div class="message-box">
					<div class="chat_box">
					<div id="messages", data-room_id="<%= @room.id %>"></div>
				    	<%= render @messages %>
				  	</div>
					<%= text_field nil, nil, 'data-behavior': 'room_speaker', placeholder: "\uf1d8", class: 'fa message-btn' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/rooms/topic.html.erb
<div id="topic">
  <h3>おすすめtopic</h3>
</div>
<% @random.each do |room| %>
  <div class="topic-box">
    <%= link_to room_path(room) do %>
      <p>ルーム：<%= room.title %></p>
      <p>内容：<%= truncate(room.detail, length: 20) %></p>
      <p>カテゴリ：<%= room.category %></p>
      <p>コメント数：<%= room.messages.count %>pt</p>
      <p style="float: left;">作成日：<%= room.created_at.strftime("%Y-%m-%d %H:%M") %></p>
      <p style="text-align:right"><%= time_ago_in_words(room.created_at) %>前</p>
    <% end %>
  </div>
<% end %>