config/routes.rb
Rails.application.routes.draw do
  #get 'categorise/index'
  #get 'categorise/show'
  get 'homes/top'
  get 'homes/about'
  get 'homes/unsubscribe'
  get 'homes/help'
  get 'rooms/search' => 'rooms#search'
  get 'rooms/topic' => 'rooms/topic'

  resources :clients, only: [:show, :edit, :update, :index, :destroy]
  get "clients/:id" => "client#show"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/sign_up/confirm' => 'users/registrations#confirm'
    post 'users/sign_up/complete' => 'users/registrations#complete'
  end

  resources :rooms, only: [:new,  :show, :index, :create] do
    post :confirm, action: :confirm, on: :new
  end

  root 'homes#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Empathy With Someone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <script src="jquery.min.js"></script>
    <script src="app.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!-- ローディング画面 -->
<div id="loader-bg">
  <div id="loader">
    <h3 class="loading-now">Now Loading...</h3>
  </div>
</div>
<div id="wrap">

  <body>
    <header class="container-fluid">
      <div class="row  h-100">
        <!-- admin用 -->
        <% if current_user.try(:admin?) %>
          <div class="header-bar">
            <h1 class="title-name">EWS</h1>
          </div>
          <div class="header-itembox col-2">
            <div class="header-items"><%= current_user.name %>さん(管理者)</div>
            <p class="header-items cp_link">
              <%= link_to rails_admin_path do %>
                <i class="fas fa-2x fa-users-cog"></i>管理
              <% end %>
            </p>
            <p class="header-items cp_link">
              <%= link_to new_room_path do %>
                <i class="fas fa-2x fa-folder-plus"></i>NEW ROOM
              <% end %>
            </p>
            <p class="header-items cp_link">
              <%= link_to rooms_path do %>
                <i class="fas fa-2x fa-comments"></i>チャットルーム一覧
                <% end %>
            </p>
            <p class="header-items cp_link">
              <%= link_to rooms_topic_path do %>
                <i class="fas fa-2x fa-chalkboard-teacher"></i>オススメ
              <% end %>
            </p>
            <p class="header-items cp_link">
              <%= link_to clients_path do%>
                <i class="fas fa-2x  fa-users"></i>ユーザ一覧
              <% end %>
            </p>
            <p class="header-items cp_link">
              <%= link_to client_path(current_user.id) do%>
                <i class="fas fa-2x fa-address-card "></i>マイページ
                <% end %>
            </p>
            <p class="header-items cp_link">

                <%= link_to homes_help_path do %>
                  <i class="fas fa-2x fa-question"></i>ヘルプ
                <% end %>
              </p>
          </div>
          <div class="col-10 foot"><%= yield %></div>

        <!-- 一般ユーザ -->
        <% elsif current_user %>
          <div class="header-bar">
            <h1 class="title-name">EWS</h1>
          </div>
          <div class="header-itembox col-2">
            <div><span class="name"><%= current_user.name %></span>さん</div>
            <p class="header-items cp_link_1">
              <%= link_to new_room_path do %>
                <i class="fas fa-2x fa-folder-plus"></i>NEW ROOM
              <% end %>
            </p>
            <p class="header-items cp_link_1">
              <%= link_to rooms_path do %>
                <i class="fas fa-2x fa-comments"></i>チャットルーム一覧
              <% end %>
            </p>
            <p class="header-items cp_link_1">
              <%= link_to rooms_topic_path do %>
                <i class="fas fa-2x fa-chalkboard-teacher"></i>オススメ
              <% end %>
            </p>
            <p class="header-items cp_link_1">
              <%= link_to clients_path do%>
                <i class="fas fa-2x  fa-users"></i>ユーザ一覧
              <% end %>
            </p>
            <p class="header-items cp_link_2">
              <%= link_to client_path(current_user.id) do%>
                <i class="fas fa-2x fa-address-card "></i>マイページ
                <% end %>
            </p>
            <p class="header-items cp_link_2">
                <%= link_to homes_help_path do %>
                  <i class="fas fa-2x fa-question"></i>ヘルプ
                <% end %>
              </p>
          </div>
          <div class="col-10 foot"><%= yield %></div>

          <!-- 未ログイン -->
          <% else %>
          <%= yield %>
        <% end %>

        <!-- admin用 -->
      </div>
    </header>
    <footer>
    <% if current_user.try(:admin?) %>
      <div id="button">footer</div>
        <div id="container">
          <div id="cont">
            <div class="copyright">
              <p>© 201805 - portfolio</p>
              <p>© Empathy With Someone</p>
            </div>
          </div>
        </div>
      </div>

      <!-- 一般ユーザ -->
      <% elsif current_user %>
      <div id="button">footer</div>
        <div id="container">
          <div id="cont">
            <div class="copyright">
              <p>© 201805 - portfolio</p>
              <p>Empathy With Someone</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <!-- 未ログイン -->
    <% else %>
    </footer>
  </body>
</html>

<!-- ダークモード -->
<!-- <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.3.4/lib/darkmode-js.min.js"></script>
<script>
  var options = {
    bottom: '90px', // default: '32px'
    right: 'unset', // default: '32px'
    left: '32px', // default: 'unset'
    time: '0.5s', // default: '0.3s'
    mixColor: '#696464', // default: '#fff'
    backgroundColor: '#fff',  // default: '#fff'
    buttonColorDark: '#100f2c',  // default: '#100f2c'
    buttonColorLight: '#fff', // default: '#fff'
    saveInCookies: false, // default: true,
    label: '🌓', // default: ''
    autoMatchOsTheme: true // default: true
  }
  const darkmode = new Darkmode(options);
  darkmode.showWidget();
</script> -->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
$(function() {
  var h = $(window).height();

  $('#wrap').css('display','none');
  $('#loader-bg ,#loader').height(h).css('display','block');
});

$(window).load(function () { //全ての読み込みが完了したら実行
  $('#loader-bg').delay(900).fadeOut(800);
  $('#loader').delay(600).fadeOut(300);
  $('#wrap').css('display', 'block');
});

//10秒たったら強制的にロード画面を非表示
$(function(){
  setTimeout('stopload()',10000);
});

function stopload(){
  $('#wrap').css('display','block');
  $('#loader-bg').delay(900).fadeOut(800);
  $('#loader').delay(600).fadeOut(300);
}
</script>